#!/usr/bin/env node
// The manifest is the single source for wire IDs, parameter/result shapes and compatibility.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const root = path.resolve(__dirname, '..');
const schema = JSON.parse(fs.readFileSync(path.join(root, 'protocol/rpc.schema.json'), 'utf8'));
schema.methods.sort((a, b) => a.id - b.id);
for (const field of ['id', 'arkName', 'goName']) {
  if (new Set(schema.methods.map(m => m[field])).size !== schema.methods.length) throw new Error(`Duplicate ${field}`);
}
const kinds = new Set(['string', 'number', 'integer', 'boolean', 'decimalString', 'object', 'array', 'json']);
function checkShape(s) {
  if (!kinds.has(s.type)) throw new Error(`Unknown shape ${s.type}`);
  if (s.type === 'array') checkShape(s.items);
  if (s.type === 'json') checkShape(s.content);
  for (const field of s.fields || []) checkShape(field.shape);
}
for (const m of schema.methods) {
  if (!Number.isSafeInteger(m.id) || m.id < 0) throw new Error('Invalid method ID');
  if (!['go', 'vpn'].includes(m.endpoint)) throw new Error('Invalid endpoint');
  let optional = false;
  for (const p of m.params) { if (optional && !p.optional) throw new Error('Required parameter after optional'); optional ||= !!p.optional; checkShape(p.shape); }
  checkShape(m.result);
}
const canonical = JSON.stringify(schema);
const hash = crypto.createHash('sha256').update(canonical).digest('hex');
const banner = '// Generated by scripts/generate-rpc.cjs from protocol/rpc.schema.json. DO NOT EDIT.\n';
const methods = schema.methods;
const ark = banner + `export const RPC_PROTOCOL_VERSION: number = ${schema.protocolVersion};
export const NATIVE_ABI_VERSION: number = ${schema.nativeAbiVersion};
export const RPC_CONTRACT_HASH: string = '${hash}';
export const RPC_CAPABILITIES: string[] = ${JSON.stringify(schema.capabilities)};
export enum ClashRpcType {
${methods.map(m => `  ${m.arkName} = ${m.id},`).join('\n')}
}
export enum RpcErrorCode {
${schema.errors.map(e => `  ${e} = '${e}',`).join('\n')}
}
export enum VpnPhase {
${schema.vpnPhases.map(phase => `  ${phase[0].toUpperCase() + phase.slice(1)} = '${phase}',`).join('\n')}
}
export interface VpnSnapshot { phase: VpnPhase; running: boolean; desiredRunning: boolean; startedAt: number; generation: number; error: string; }
export type RpcValue = string | number | boolean;
export interface RpcRequest { protocolVersion: number; method: number; params: RpcValue[]; }
export interface RpcResult { protocolVersion: number; method: number; result?: RpcValue; error?: string; errorCode?: RpcErrorCode; streamReady?: boolean; }
export interface RpcCapabilities { protocolVersion: number; nativeAbiVersion: number; contractHash: string; coreVersion: string; capabilities: string[]; }
export interface RpcShape { type: string; nullable?: boolean; minLength?: number; min?: number; max?: number; enum?: string[]; fields?: RpcField[]; items?: RpcShape; content?: RpcShape; }
export interface RpcField { name: string; shape: RpcShape; optional?: boolean; }
export interface RpcMethodSpec { id: number; arkName: string; goName: string; endpoint: string; supported: boolean; stream: boolean; params: RpcField[]; result: RpcShape; }
export const RPC_METHODS: RpcMethodSpec[] = ${JSON.stringify(methods, null, 2)};
`;
const go = banner + `package rpccontract\n\nconst ProtocolVersion = ${schema.protocolVersion}\nconst NativeABIVersion = ${schema.nativeAbiVersion}\nconst ContractHash = "${hash}"\n\n` +
  methods.map(m => `const ${m.goName} = ${m.id}\n`).join('') + '\n' +
  schema.errors.map(e => `const ${e} = "${e}"\n`).join('') +
  `\nconst schemaJSON = ${JSON.stringify(canonical)}\n`;
const aliases = banner + 'package main\n\nimport "core/rpccontract"\n\ntype ClashRpcType = int\ntype RpcRequest = rpccontract.Request\ntype RpcResult = rpccontract.Response\n\n' +
  methods.map(m => `const ${m.goName} = rpccontract.${m.goName}\n`).join('');
const outputs = {
  'proxy_core/src/main/ets/rpc/RpcContract.generated.ts': ark,
  'proxy_core/src/flclash/rpccontract/schema_generated.go': go,
  'proxy_core/src/flclash/ipc_contract_generated.go': aliases
};
for (const [name, content] of Object.entries(outputs)) {
  const target = path.join(root, name);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) {
      console.error(`Stale RPC definition: ${name}; run node scripts/generate-rpc.cjs`); process.exitCode = 1;
    }
  } else { fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, content); }
}
