// Generated by scripts/generate-rpc.cjs from protocol/rpc.schema.json. DO NOT EDIT.
package main

import "core/rpccontract"

type ClashRpcType = int
type RpcRequest = rpccontract.Request
type RpcResult = rpccontract.Response

const QueryTrafficNow = rpccontract.QueryTrafficNow
const QueryTunnelState = rpccontract.QueryTunnelState
const QueryTrafficTotal = rpccontract.QueryTrafficTotal
const QueryProxyGroup = rpccontract.QueryProxyGroup
const QueryProviders = rpccontract.QueryProviders
const ChangeProxy = rpccontract.ChangeProxy
const HealthCheck = rpccontract.HealthCheck
const UpdateProvider = rpccontract.UpdateProvider
const UploadProvider = rpccontract.UploadProvider
const QueryConnections = rpccontract.QueryConnections
const CloseConnection = rpccontract.CloseConnection
const ClearConnections = rpccontract.ClearConnections
const Load = rpccontract.Load
const StartClash = rpccontract.StartClash
const StopClash = rpccontract.StopClash
const ValidConfig = rpccontract.ValidConfig
const Reset = rpccontract.Reset
const GetCountryCode = rpccontract.GetCountryCode
const UpdateGeoData = rpccontract.UpdateGeoData
const RegisterOnMessage = rpccontract.RegisterOnMessage
const GetRequestList = rpccontract.GetRequestList
const ClearRequestList = rpccontract.ClearRequestList
const SetLogObserver = rpccontract.SetLogObserver
const StopLogObserver = rpccontract.StopLogObserver
const VpnOptions = rpccontract.VpnOptions
const SetOptionState = rpccontract.SetOptionState
const GetVpnRunTime = rpccontract.GetVpnRunTime
const VpnConfigInited = rpccontract.VpnConfigInited
const SetNetInterfaces = rpccontract.SetNetInterfaces
const DownloadConfig = rpccontract.DownloadConfig
const SetSystemDns = rpccontract.SetSystemDns
const HealthCheckAll = rpccontract.HealthCheckAll
const HealthCheckBatch = rpccontract.HealthCheckBatch
const GetVersion = rpccontract.GetVersion
const GetCapabilities = rpccontract.GetCapabilities
